apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: '{{ .Release.Name }}'
    namespace: '{{ .Release.Namespace }}'
    {{- if .Values.ingress.annotations }}
    annotations:
      {{- range $key, $value := .Values.ingress.annotations }}
      {{ $key }}: {{ tpl $value $ | quote }}
      {{- end }}
    {{- end }}
spec:
    tls:
    - hosts:
      - "{{ .Values.domainPrefix }}.{{ .Values.cluster.apiDomainName }}"
      - "{{ .Values.domainPrefix }}.{{ .Values.global.apiDomainName }}"
      secretName: "{{ .Release.Name }}-tls"

    rules:
    - host: "{{ .Values.domainPrefix }}.{{ .Values.cluster.apiDomainName }}"
      http:
        paths:
        - backend:
            serviceName: '{{ .Release.Name }}'
            servicePort: {{ .Values.servicePort }}
          path: /
    - host: "{{ .Values.domainPrefix }}.{{ .Values.global.apiDomainName }}"
      http:
        paths:
        - backend:
            serviceName: '{{ .Release.Name }}'
            servicePort: {{ .Values.servicePort }}
          path: /